/*
 * ProvisioningAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 01/29/2015
 */
package com.voxbone.sandbox;

public class Configuration {
    //The base Uri for API calls
    public static final String baseUri = "http://sandbox.voxbone.com/ws-voxbone";

}
