/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox;

import java.io.InputStream;

public class APIError extends Error {
    //UID for serialization
    private static final long serialVersionUID = 6424174253911720338L;

    //private fields
    private int responseCode;

    //private fields
    private InputStream rawBody;

    /**
    * The HTTP response code from the API request
    */
    public int getResponseCode() {
        return responseCode;
    }

    /**
     * The HTTP response body from the API request
     */
    public InputStream getRawBody() {
        return rawBody;
    }

    /**
    * Initialization constructor
    * @param	reason	The reason for throwing exception
    * @param	code	The HTTP response code from the API request
    */
    public APIError(String reason, int code, InputStream body) {
        super(reason);
        this.responseCode = code;
        this.rawBody = body;
    }

    /**
     * Initialization constructor
     * @param	reason	The reason for throwing exception
     */
    public APIError(String reason) {
        super(reason);
    }
}