/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class AddressListModel 
        implements java.io.Serializable {

    private List<AddressModel> regulationAddresses;
    private int resultCount;
    /** GETTER
     * The list of addresses
     */
    @JsonGetter("regulationAddresses")
    public List<AddressModel> getRegulationAddresses ( ) { 
        return this.regulationAddresses;
    }
    
    /** SETTER
     * The list of addresses
     */
    @JsonSetter("regulationAddresses")
    public void setRegulationAddresses (List<AddressModel> value) { 
        this.regulationAddresses = value;
    }
 
    /** GETTER
     * The total amount of addresses found
     */
    @JsonGetter("resultCount")
    public int getResultCount ( ) { 
        return this.resultCount;
    }
    
    /** SETTER
     * The total amount of addresses found
     */
    @JsonSetter("resultCount")
    public void setResultCount (int value) { 
        this.resultCount = value;
    }
 
}
 