/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class AVoiceUriSaveModel 
        implements java.io.Serializable {

    private VoiceUriSaveModel voiceUri;
    /** GETTER
     * Grouping of VoiceUriSave
     */
    @JsonGetter("voiceUri")
    public VoiceUriSaveModel getVoiceUri ( ) { 
        return this.voiceUri;
    }
    
    /** SETTER
     * Grouping of VoiceUriSave
     */
    @JsonSetter("voiceUri")
    public void setVoiceUri (VoiceUriSaveModel value) { 
        this.voiceUri = value;
    }
 
}
 