/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CallerIdModel 
        implements java.io.Serializable {

    private String cliFormat;
    private String cliValue;
    /** GETTER
     * The CLI format
     */
    @JsonGetter("cliFormat")
    public String getCliFormat ( ) { 
        return this.cliFormat;
    }
    
    /** SETTER
     * The CLI format
     */
    @JsonSetter("cliFormat")
    public void setCliFormat (String value) { 
        this.cliFormat = value;
    }
 
    /** GETTER
     * The CLI prefix
     */
    @JsonGetter("cliValue")
    public String getCliValue ( ) { 
        return this.cliValue;
    }
    
    /** SETTER
     * The CLI prefix
     */
    @JsonSetter("cliValue")
    public void setCliValue (String value) { 
        this.cliValue = value;
    }
 
}
 