/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CapacityGroupListModel 
        implements java.io.Serializable {

    private List<CapacityGroupModel> capacityGroups;
    private int resultCount;
    /** GETTER
     * The list of capacity groups
     */
    @JsonGetter("capacityGroups")
    public List<CapacityGroupModel> getCapacityGroups ( ) { 
        return this.capacityGroups;
    }
    
    /** SETTER
     * The list of capacity groups
     */
    @JsonSetter("capacityGroups")
    public void setCapacityGroups (List<CapacityGroupModel> value) { 
        this.capacityGroups = value;
    }
 
    /** GETTER
     * The total amount of capacity groups found
     */
    @JsonGetter("resultCount")
    public int getResultCount ( ) { 
        return this.resultCount;
    }
    
    /** SETTER
     * The total amount of capacity groups found
     */
    @JsonSetter("resultCount")
    public void setResultCount (int value) { 
        this.resultCount = value;
    }
 
}
 