/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CapacityGroupModel 
        implements java.io.Serializable {

    private int capacityGroupId;
    private int maximumCapacity;
    private int amountOfDidsMapped;
    private String description;
    /** GETTER
     * The identifier of the capacity group
     */
    @JsonGetter("capacityGroupId")
    public int getCapacityGroupId ( ) { 
        return this.capacityGroupId;
    }
    
    /** SETTER
     * The identifier of the capacity group
     */
    @JsonSetter("capacityGroupId")
    public void setCapacityGroupId (int value) { 
        this.capacityGroupId = value;
    }
 
    /** GETTER
     * The maximum capacity of the capacity group
     */
    @JsonGetter("maximumCapacity")
    public int getMaximumCapacity ( ) { 
        return this.maximumCapacity;
    }
    
    /** SETTER
     * The maximum capacity of the capacity group
     */
    @JsonSetter("maximumCapacity")
    public void setMaximumCapacity (int value) { 
        this.maximumCapacity = value;
    }
 
    /** GETTER
     * The amount of DIDs currently mapped to the capacity group
     */
    @JsonGetter("amountOfDidsMapped")
    public int getAmountOfDidsMapped ( ) { 
        return this.amountOfDidsMapped;
    }
    
    /** SETTER
     * The amount of DIDs currently mapped to the capacity group
     */
    @JsonSetter("amountOfDidsMapped")
    public void setAmountOfDidsMapped (int value) { 
        this.amountOfDidsMapped = value;
    }
 
    /** GETTER
     * A human readable description of the capacity group
     */
    @JsonGetter("description")
    public String getDescription ( ) { 
        return this.description;
    }
    
    /** SETTER
     * A human readable description of the capacity group
     */
    @JsonSetter("description")
    public void setDescription (String value) { 
        this.description = value;
    }
 
}
 