/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CapacityCartItemModel 
        implements java.io.Serializable {

    private String zone;
    private int quantity;
    /** GETTER
     * The zone to order capacity for
     */
    @JsonGetter("zone")
    public String getZone ( ) { 
        return this.zone;
    }
    
    /** SETTER
     * The zone to order capacity for
     */
    @JsonSetter("zone")
    public void setZone (String value) { 
        this.zone = value;
    }
 
    /** GETTER
     * The amount of channels to order
     */
    @JsonGetter("quantity")
    public int getQuantity ( ) { 
        return this.quantity;
    }
    
    /** SETTER
     * The amount of channels to order
     */
    @JsonSetter("quantity")
    public void setQuantity (int value) { 
        this.quantity = value;
    }
 
}
 