/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CartListModel 
        implements java.io.Serializable {

    private List<CartModel> carts;
    private int resultCount;
    /** GETTER
     * The list of carts
     */
    @JsonGetter("carts")
    public List<CartModel> getCarts ( ) { 
        return this.carts;
    }
    
    /** SETTER
     * The list of carts
     */
    @JsonSetter("carts")
    public void setCarts (List<CartModel> value) { 
        this.carts = value;
    }
 
    /** GETTER
     * The total amount of carts found
     */
    @JsonGetter("resultCount")
    public int getResultCount ( ) { 
        return this.resultCount;
    }
    
    /** SETTER
     * The total amount of carts found
     */
    @JsonSetter("resultCount")
    public void setResultCount (int value) { 
        this.resultCount = value;
    }
 
}
 