/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CartCreateModel 
        implements java.io.Serializable {

    private String customerReference;
    private String description;
    /** GETTER
     * The custom reference to assign to this cart
     */
    @JsonGetter("customerReference")
    public String getCustomerReference ( ) { 
        return this.customerReference;
    }
    
    /** SETTER
     * The custom reference to assign to this cart
     */
    @JsonSetter("customerReference")
    public void setCustomerReference (String value) { 
        this.customerReference = value;
    }
 
    /** GETTER
     * A human readable description of the cart
     */
    @JsonGetter("description")
    public String getDescription ( ) { 
        return this.description;
    }
    
    /** SETTER
     * A human readable description of the cart
     */
    @JsonSetter("description")
    public void setDescription (String value) { 
        this.description = value;
    }
 
}
 