/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CartCheckoutModel 
        implements java.io.Serializable {

    private String status;
    private List<ProductCheckoutModel> productCheckoutList;
    /** GETTER
     * The global status for the checkout
     */
    @JsonGetter("status")
    public String getStatus ( ) { 
        return this.status;
    }
    
    /** SETTER
     * The global status for the checkout
     */
    @JsonSetter("status")
    public void setStatus (String value) { 
        this.status = value;
    }
 
    /** GETTER
     * The list of individual product checkout results
     */
    @JsonGetter("productCheckoutList")
    public List<ProductCheckoutModel> getProductCheckoutList ( ) { 
        return this.productCheckoutList;
    }
    
    /** SETTER
     * The list of individual product checkout results
     */
    @JsonSetter("productCheckoutList")
    public void setProductCheckoutList (List<ProductCheckoutModel> value) { 
        this.productCheckoutList = value;
    }
 
}
 