/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CartItemModel 
        implements java.io.Serializable {

    private DidCartItemModel didCartItem;
    private CapacityCartItemModel capacityCartItem;
    private CreditPackageCartItemModel creditPackageCartItem;
    /** GETTER
     * A cart item for DIDs
     */
    @JsonGetter("didCartItem")
    public DidCartItemModel getDidCartItem ( ) { 
        return this.didCartItem;
    }
    
    /** SETTER
     * A cart item for DIDs
     */
    @JsonSetter("didCartItem")
    public void setDidCartItem (DidCartItemModel value) { 
        this.didCartItem = value;
    }
 
    /** GETTER
     * A cart item for capacity
     */
    @JsonGetter("capacityCartItem")
    public CapacityCartItemModel getCapacityCartItem ( ) { 
        return this.capacityCartItem;
    }
    
    /** SETTER
     * A cart item for capacity
     */
    @JsonSetter("capacityCartItem")
    public void setCapacityCartItem (CapacityCartItemModel value) { 
        this.capacityCartItem = value;
    }
 
    /** GETTER
     * A cart item for credit packages
     */
    @JsonGetter("creditPackageCartItem")
    public CreditPackageCartItemModel getCreditPackageCartItem ( ) { 
        return this.creditPackageCartItem;
    }
    
    /** SETTER
     * A cart item for credit packages
     */
    @JsonSetter("creditPackageCartItem")
    public void setCreditPackageCartItem (CreditPackageCartItemModel value) { 
        this.creditPackageCartItem = value;
    }
 
}
 