/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import java.util.Date;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CartModel 
        implements java.io.Serializable {

    private int cartIdentifier;
    private String customerReference;
    private String description;
    private Date dateAdded;
    private List<OrderProductModel> orderProducts;
    /** GETTER
     * The identifier of the cart
     */
    @JsonGetter("cartIdentifier")
    public int getCartIdentifier ( ) { 
        return this.cartIdentifier;
    }
    
    /** SETTER
     * The identifier of the cart
     */
    @JsonSetter("cartIdentifier")
    public void setCartIdentifier (int value) { 
        this.cartIdentifier = value;
    }
 
    /** GETTER
     * The custom reference given upon cart creation
     */
    @JsonGetter("customerReference")
    public String getCustomerReference ( ) { 
        return this.customerReference;
    }
    
    /** SETTER
     * The custom reference given upon cart creation
     */
    @JsonSetter("customerReference")
    public void setCustomerReference (String value) { 
        this.customerReference = value;
    }
 
    /** GETTER
     * A human readable description of the cart
     */
    @JsonGetter("description")
    public String getDescription ( ) { 
        return this.description;
    }
    
    /** SETTER
     * A human readable description of the cart
     */
    @JsonSetter("description")
    public void setDescription (String value) { 
        this.description = value;
    }
 
    /** GETTER
     * The creation date of the cart
     */
    @JsonGetter("dateAdded")
    public Date getDateAdded ( ) { 
        return this.dateAdded;
    }
    
    /** SETTER
     * The creation date of the cart
     */
    @JsonSetter("dateAdded")
    public void setDateAdded (Date value) { 
        this.dateAdded = value;
    }
 
    /** GETTER
     * The list of products currently in the cart
     */
    @JsonGetter("orderProducts")
    public List<OrderProductModel> getOrderProducts ( ) { 
        return this.orderProducts;
    }
    
    /** SETTER
     * The list of products currently in the cart
     */
    @JsonSetter("orderProducts")
    public void setOrderProducts (List<OrderProductModel> value) { 
        this.orderProducts = value;
    }
 
}
 