/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ConfigurationStatusListModel 
        implements java.io.Serializable {

    private List<ConfigurationStatusModel> messages;
    /** GETTER
     * The list of configuration statuses
     */
    @JsonGetter("messages")
    public List<ConfigurationStatusModel> getMessages ( ) { 
        return this.messages;
    }
    
    /** SETTER
     * The list of configuration statuses
     */
    @JsonSetter("messages")
    public void setMessages (List<ConfigurationStatusModel> value) { 
        this.messages = value;
    }
 
}
 