/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CountryListModel 
        implements java.io.Serializable {

    private List<CountryModel> countries;
    private int resultCount;
    /** GETTER
     * The list of countries
     */
    @JsonGetter("countries")
    public List<CountryModel> getCountries ( ) { 
        return this.countries;
    }
    
    /** SETTER
     * The list of countries
     */
    @JsonSetter("countries")
    public void setCountries (List<CountryModel> value) { 
        this.countries = value;
    }
 
    /** GETTER
     * The total amount of countries
     */
    @JsonGetter("resultCount")
    public int getResultCount ( ) { 
        return this.resultCount;
    }
    
    /** SETTER
     * The total amount of countries
     */
    @JsonSetter("resultCount")
    public void setResultCount (int value) { 
        this.resultCount = value;
    }
 
}
 