/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CreditPackageListModel 
        implements java.io.Serializable {

    private List<CreditPackageModel> creditPackages;
    /** GETTER
     * The list of credit packages
     */
    @JsonGetter("creditPackages")
    public List<CreditPackageModel> getCreditPackages ( ) { 
        return this.creditPackages;
    }
    
    /** SETTER
     * The list of credit packages
     */
    @JsonSetter("creditPackages")
    public void setCreditPackages (List<CreditPackageModel> value) { 
        this.creditPackages = value;
    }
 
}
 