/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CreditPackageModel 
        implements java.io.Serializable {

    private int creditPackageId;
    private String name;
    private String price100;
    /** GETTER
     * The identifier of the credit package
     */
    @JsonGetter("creditPackageId")
    public int getCreditPackageId ( ) { 
        return this.creditPackageId;
    }
    
    /** SETTER
     * The identifier of the credit package
     */
    @JsonSetter("creditPackageId")
    public void setCreditPackageId (int value) { 
        this.creditPackageId = value;
    }
 
    /** GETTER
     * The name of the credit package
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * The name of the credit package
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * The price of the credit package in cents
     */
    @JsonGetter("price100")
    public String getPrice100 ( ) { 
        return this.price100;
    }
    
    /** SETTER
     * The price of the credit package in cents
     */
    @JsonSetter("price100")
    public void setPrice100 (String value) { 
        this.price100 = value;
    }
 
}
 