/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CreditPackageCartItemModel 
        implements java.io.Serializable {

    private int creditPackageId;
    private int quantity;
    /** GETTER
     * The identifier of the credit package to order
     */
    @JsonGetter("creditPackageId")
    public int getCreditPackageId ( ) { 
        return this.creditPackageId;
    }
    
    /** SETTER
     * The identifier of the credit package to order
     */
    @JsonSetter("creditPackageId")
    public void setCreditPackageId (int value) { 
        this.creditPackageId = value;
    }
 
    /** GETTER
     * The quantity of packages to order
     */
    @JsonGetter("quantity")
    public int getQuantity ( ) { 
        return this.quantity;
    }
    
    /** SETTER
     * The quantity of packages to order
     */
    @JsonSetter("quantity")
    public void setQuantity (int value) { 
        this.quantity = value;
    }
 
}
 