/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class DidCartItemModel 
        implements java.io.Serializable {

    private int didGroupId;
    private int quantity;
    /** GETTER
     * The identifier of the didGroup to order from
     */
    @JsonGetter("didGroupId")
    public int getDidGroupId ( ) { 
        return this.didGroupId;
    }
    
    /** SETTER
     * The identifier of the didGroup to order from
     */
    @JsonSetter("didGroupId")
    public void setDidGroupId (int value) { 
        this.didGroupId = value;
    }
 
    /** GETTER
     * The quantity to order
     */
    @JsonGetter("quantity")
    public int getQuantity ( ) { 
        return this.quantity;
    }
    
    /** SETTER
     * The quantity to order
     */
    @JsonSetter("quantity")
    public void setQuantity (int value) { 
        this.quantity = value;
    }
 
}
 