/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class DidGroupListModel 
        implements java.io.Serializable {

    private List<DidGroupModel> didGroups;
    private int resultCount;
    /** GETTER
     * The list of didgroups
     */
    @JsonGetter("didGroups")
    public List<DidGroupModel> getDidGroups ( ) { 
        return this.didGroups;
    }
    
    /** SETTER
     * The list of didgroups
     */
    @JsonSetter("didGroups")
    public void setDidGroups (List<DidGroupModel> value) { 
        this.didGroups = value;
    }
 
    /** GETTER
     * The total amount of didgroups
     */
    @JsonGetter("resultCount")
    public int getResultCount ( ) { 
        return this.resultCount;
    }
    
    /** SETTER
     * The total amount of didgroups
     */
    @JsonSetter("resultCount")
    public void setResultCount (int value) { 
        this.resultCount = value;
    }
 
}
 