/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class DidIdModel 
        implements java.io.Serializable {

    private int didId;
    /** GETTER
     * DID Id
     */
    @JsonGetter("didId")
    public int getDidId ( ) { 
        return this.didId;
    }
    
    /** SETTER
     * DID Id
     */
    @JsonSetter("didId")
    public void setDidId (int value) { 
        this.didId = value;
    }
 
}
 