/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class DidIdListModel 
        implements java.io.Serializable {

    private List<DidIdModel> didIds;
    /** GETTER
     * Array of DID ids
     */
    @JsonGetter("didIds")
    public List<DidIdModel> getDidIds ( ) { 
        return this.didIds;
    }
    
    /** SETTER
     * Array of DID ids
     */
    @JsonSetter("didIds")
    public void setDidIds (List<DidIdModel> value) { 
        this.didIds = value;
    }
 
}
 