/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class DidListModel 
        implements java.io.Serializable {

    private List<DidModel> dids;
    private int resultCount;
    /** GETTER
     * The list of DIDs
     */
    @JsonGetter("dids")
    public List<DidModel> getDids ( ) { 
        return this.dids;
    }
    
    /** SETTER
     * The list of DIDs
     */
    @JsonSetter("dids")
    public void setDids (List<DidModel> value) { 
        this.dids = value;
    }
 
    /** GETTER
     * The total amount of DIDs found
     */
    @JsonGetter("resultCount")
    public int getResultCount ( ) { 
        return this.resultCount;
    }
    
    /** SETTER
     * The total amount of DIDs found
     */
    @JsonSetter("resultCount")
    public void setResultCount (int value) { 
        this.resultCount = value;
    }
 
}
 