/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class FaxUriSaveModel 
        implements java.io.Serializable {

    private FaxUriModel faxUri;
    /** GETTER
     * Grouping of faxUri
     */
    @JsonGetter("faxUri")
    public FaxUriModel getFaxUri ( ) { 
        return this.faxUri;
    }
    
    /** SETTER
     * Grouping of faxUri
     */
    @JsonSetter("faxUri")
    public void setFaxUri (FaxUriModel value) { 
        this.faxUri = value;
    }
 
}
 