/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class FaxUriListModel 
        implements java.io.Serializable {

    private List<FaxUriModel> faxUris;
    private int resultCount;
    /** GETTER
     * The list of fax URIs
     */
    @JsonGetter("faxUris")
    public List<FaxUriModel> getFaxUris ( ) { 
        return this.faxUris;
    }
    
    /** SETTER
     * The list of fax URIs
     */
    @JsonSetter("faxUris")
    public void setFaxUris (List<FaxUriModel> value) { 
        this.faxUris = value;
    }
 
    /** GETTER
     * The total amount of fax URIs found
     */
    @JsonGetter("resultCount")
    public int getResultCount ( ) { 
        return this.resultCount;
    }
    
    /** SETTER
     * The total amount of fax URIs found
     */
    @JsonSetter("resultCount")
    public void setResultCount (int value) { 
        this.resultCount = value;
    }
 
}
 