/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class FaxUriModel 
        implements java.io.Serializable {

    private int faxUriId;
    private String deliveryMethod;
    private String faxFileFormat;
    private String uri;
    private String csid;
    private String subject;
    private String body;
    private boolean useHtml;
    /** GETTER
     * The identifier of the fax URI
     */
    @JsonGetter("faxUriId")
    public int getFaxUriId ( ) { 
        return this.faxUriId;
    }
    
    /** SETTER
     * The identifier of the fax URI
     */
    @JsonSetter("faxUriId")
    public void setFaxUriId (int value) { 
        this.faxUriId = value;
    }
 
    /** GETTER
     * The delivery method used by the fax URI
     */
    @JsonGetter("deliveryMethod")
    public String getDeliveryMethod ( ) { 
        return this.deliveryMethod;
    }
    
    /** SETTER
     * The delivery method used by the fax URI
     */
    @JsonSetter("deliveryMethod")
    public void setDeliveryMethod (String value) { 
        this.deliveryMethod = value;
    }
 
    /** GETTER
     * The file format used by the fax URI
     */
    @JsonGetter("faxFileFormat")
    public String getFaxFileFormat ( ) { 
        return this.faxFileFormat;
    }
    
    /** SETTER
     * The file format used by the fax URI
     */
    @JsonSetter("faxFileFormat")
    public void setFaxFileFormat (String value) { 
        this.faxFileFormat = value;
    }
 
    /** GETTER
     * The formatted URI
     */
    @JsonGetter("uri")
    public String getUri ( ) { 
        return this.uri;
    }
    
    /** SETTER
     * The formatted URI
     */
    @JsonSetter("uri")
    public void setUri (String value) { 
        this.uri = value;
    }
 
    /** GETTER
     * The csid used by the fax URI
     */
    @JsonGetter("csid")
    public String getCsid ( ) { 
        return this.csid;
    }
    
    /** SETTER
     * The csid used by the fax URI
     */
    @JsonSetter("csid")
    public void setCsid (String value) { 
        this.csid = value;
    }
 
    /** GETTER
     * The text to use as subject line
     */
    @JsonGetter("subject")
    public String getSubject ( ) { 
        return this.subject;
    }
    
    /** SETTER
     * The text to use as subject line
     */
    @JsonSetter("subject")
    public void setSubject (String value) { 
        this.subject = value;
    }
 
    /** GETTER
     * The text to use in the body
     */
    @JsonGetter("body")
    public String getBody ( ) { 
        return this.body;
    }
    
    /** SETTER
     * The text to use in the body
     */
    @JsonSetter("body")
    public void setBody (String value) { 
        this.body = value;
    }
 
    /** GETTER
     * A flag indicating if the fax uses HTML
     */
    @JsonGetter("useHtml")
    public boolean getUseHtml ( ) { 
        return this.useHtml;
    }
    
    /** SETTER
     * A flag indicating if the fax uses HTML
     */
    @JsonSetter("useHtml")
    public void setUseHtml (boolean value) { 
        this.useHtml = value;
    }
 
}
 