/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class OrderProductModel 
        implements java.io.Serializable {

    private int orderProductId;
    private String productType;
    private String productDescription;
    private int quantity;
    private int didgroupId;
    /** GETTER
     * The identifier of the product
     */
    @JsonGetter("orderProductId")
    public int getOrderProductId ( ) { 
        return this.orderProductId;
    }
    
    /** SETTER
     * The identifier of the product
     */
    @JsonSetter("orderProductId")
    public void setOrderProductId (int value) { 
        this.orderProductId = value;
    }
 
    /** GETTER
     * The type of product
     */
    @JsonGetter("productType")
    public String getProductType ( ) { 
        return this.productType;
    }
    
    /** SETTER
     * The type of product
     */
    @JsonSetter("productType")
    public void setProductType (String value) { 
        this.productType = value;
    }
 
    /** GETTER
     * A human readable description of the product
     */
    @JsonGetter("productDescription")
    public String getProductDescription ( ) { 
        return this.productDescription;
    }
    
    /** SETTER
     * A human readable description of the product
     */
    @JsonSetter("productDescription")
    public void setProductDescription (String value) { 
        this.productDescription = value;
    }
 
    /** GETTER
     * The quantity of products ordered
     */
    @JsonGetter("quantity")
    public int getQuantity ( ) { 
        return this.quantity;
    }
    
    /** SETTER
     * The quantity of products ordered
     */
    @JsonSetter("quantity")
    public void setQuantity (int value) { 
        this.quantity = value;
    }
 
    /** GETTER
     * The identifier of the didGroup for DID products
     */
    @JsonGetter("didgroupId")
    public int getDidgroupId ( ) { 
        return this.didgroupId;
    }
    
    /** SETTER
     * The identifier of the didGroup for DID products
     */
    @JsonSetter("didgroupId")
    public void setDidgroupId (int value) { 
        this.didgroupId = value;
    }
 
}
 