/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class OrderListModel 
        implements java.io.Serializable {

    private List<OrderModel> orders;
    private int resultCount;
    /** GETTER
     * The list of orders
     */
    @JsonGetter("orders")
    public List<OrderModel> getOrders ( ) { 
        return this.orders;
    }
    
    /** SETTER
     * The list of orders
     */
    @JsonSetter("orders")
    public void setOrders (List<OrderModel> value) { 
        this.orders = value;
    }
 
    /** GETTER
     * The total amount of orders found
     */
    @JsonGetter("resultCount")
    public int getResultCount ( ) { 
        return this.resultCount;
    }
    
    /** SETTER
     * The total amount of orders found
     */
    @JsonSetter("resultCount")
    public void setResultCount (int value) { 
        this.resultCount = value;
    }
 
}
 