/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class OrderModel 
        implements java.io.Serializable {

    private int orderId;
    private String reference;
    private String dateAdded;
    private String dateCanceled;
    private String status;
    /** GETTER
     * The identifier of the order
     */
    @JsonGetter("orderId")
    public int getOrderId ( ) { 
        return this.orderId;
    }
    
    /** SETTER
     * The identifier of the order
     */
    @JsonSetter("orderId")
    public void setOrderId (int value) { 
        this.orderId = value;
    }
 
    /** GETTER
     * The reference assigned to the order by Voxbone
     */
    @JsonGetter("reference")
    public String getReference ( ) { 
        return this.reference;
    }
    
    /** SETTER
     * The reference assigned to the order by Voxbone
     */
    @JsonSetter("reference")
    public void setReference (String value) { 
        this.reference = value;
    }
 
    /** GETTER
     * The order creation date
     */
    @JsonGetter("dateAdded")
    public String getDateAdded ( ) { 
        return this.dateAdded;
    }
    
    /** SETTER
     * The order creation date
     */
    @JsonSetter("dateAdded")
    public void setDateAdded (String value) { 
        this.dateAdded = value;
    }
 
    /** GETTER
     * The order cancellation date, if applicable
     */
    @JsonGetter("dateCanceled")
    public String getDateCanceled ( ) { 
        return this.dateCanceled;
    }
    
    /** SETTER
     * The order cancellation date, if applicable
     */
    @JsonSetter("dateCanceled")
    public void setDateCanceled (String value) { 
        this.dateCanceled = value;
    }
 
    /** GETTER
     * The current status of the order
     */
    @JsonGetter("status")
    public String getStatus ( ) { 
        return this.status;
    }
    
    /** SETTER
     * The current status of the order
     */
    @JsonSetter("status")
    public void setStatus (String value) { 
        this.status = value;
    }
 
}
 