/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class PopListModel 
        implements java.io.Serializable {

    private List<PopModel> pops;
    /** GETTER
     * The list of POPs
     */
    @JsonGetter("pops")
    public List<PopModel> getPops ( ) { 
        return this.pops;
    }
    
    /** SETTER
     * The list of POPs
     */
    @JsonSetter("pops")
    public void setPops (List<PopModel> value) { 
        this.pops = value;
    }
 
}
 