/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ProductCheckoutModel 
        implements java.io.Serializable {

    private String productType;
    private String status;
    private String orderReference;
    /** GETTER
     * The product type (DID / CAPACITY / CREDIT_PACKAGE)
     */
    @JsonGetter("productType")
    public String getProductType ( ) { 
        return this.productType;
    }
    
    /** SETTER
     * The product type (DID / CAPACITY / CREDIT_PACKAGE)
     */
    @JsonSetter("productType")
    public void setProductType (String value) { 
        this.productType = value;
    }
 
    /** GETTER
     * The status of the checkout
     */
    @JsonGetter("status")
    public String getStatus ( ) { 
        return this.status;
    }
    
    /** SETTER
     * The status of the checkout
     */
    @JsonSetter("status")
    public void setStatus (String value) { 
        this.status = value;
    }
 
    /** GETTER
     * The reference of the newly created order
     */
    @JsonGetter("orderReference")
    public String getOrderReference ( ) { 
        return this.orderReference;
    }
    
    /** SETTER
     * The reference of the newly created order
     */
    @JsonSetter("orderReference")
    public void setOrderReference (String value) { 
        this.orderReference = value;
    }
 
}
 