/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class RegulationRequirementModel 
        implements java.io.Serializable {

    private String addressType;
    private boolean proofRequired;
    /** GETTER
     * The type of address required to activate numbers in this didgroup
     */
    @JsonGetter("addressType")
    public String getAddressType ( ) { 
        return this.addressType;
    }
    
    /** SETTER
     * The type of address required to activate numbers in this didgroup
     */
    @JsonSetter("addressType")
    public void setAddressType (String value) { 
        this.addressType = value;
    }
 
    /** GETTER
     * A flag indicating if a proof of address is required
     */
    @JsonGetter("proofRequired")
    public boolean getProofRequired ( ) { 
        return this.proofRequired;
    }
    
    /** SETTER
     * A flag indicating if a proof of address is required
     */
    @JsonSetter("proofRequired")
    public void setProofRequired (boolean value) { 
        this.proofRequired = value;
    }
 
}
 