/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class RestrictionModel 
        implements java.io.Serializable {

    private String countryCodeA3;
    private String restrictionType;
    private String restrictionMessage;
    /** GETTER
     * The three letter identifier of the country
     */
    @JsonGetter("countryCodeA3")
    public String getCountryCodeA3 ( ) { 
        return this.countryCodeA3;
    }
    
    /** SETTER
     * The three letter identifier of the country
     */
    @JsonSetter("countryCodeA3")
    public void setCountryCodeA3 (String value) { 
        this.countryCodeA3 = value;
    }
 
    /** GETTER
     * The restriction type
     */
    @JsonGetter("restrictionType")
    public String getRestrictionType ( ) { 
        return this.restrictionType;
    }
    
    /** SETTER
     * The restriction type
     */
    @JsonSetter("restrictionType")
    public void setRestrictionType (String value) { 
        this.restrictionType = value;
    }
 
    /** GETTER
     * A human readable description of the restriction
     */
    @JsonGetter("restrictionMessage")
    public String getRestrictionMessage ( ) { 
        return this.restrictionMessage;
    }
    
    /** SETTER
     * A human readable description of the restriction
     */
    @JsonSetter("restrictionMessage")
    public void setRestrictionMessage (String value) { 
        this.restrictionMessage = value;
    }
 
}
 