/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class SmsLinkGroupListModel 
        implements java.io.Serializable {

    private List<SmsLinkGroupModel> smsLinkGroups;
    /** GETTER
     * The list of sms link groups
     */
    @JsonGetter("smsLinkGroups")
    public List<SmsLinkGroupModel> getSmsLinkGroups ( ) { 
        return this.smsLinkGroups;
    }
    
    /** SETTER
     * The list of sms link groups
     */
    @JsonSetter("smsLinkGroups")
    public void setSmsLinkGroups (List<SmsLinkGroupModel> value) { 
        this.smsLinkGroups = value;
    }
 
}
 