/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class SmsLinkListModel 
        implements java.io.Serializable {

    private List<SmsLinkModel> smsLinks;
    /** GETTER
     * The list of sms links
     */
    @JsonGetter("smsLinks")
    public List<SmsLinkModel> getSmsLinks ( ) { 
        return this.smsLinks;
    }
    
    /** SETTER
     * The list of sms links
     */
    @JsonSetter("smsLinks")
    public void setSmsLinks (List<SmsLinkModel> value) { 
        this.smsLinks = value;
    }
 
}
 