/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class SmsLinkGroupSaveModel 
        implements java.io.Serializable {

    private String name;
    /** GETTER
     * The name of the sms link group
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * The name of the sms link group
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
}
 