/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class SmsLinkModel 
        implements java.io.Serializable {

    private int smsLinkId;
    private int groupId;
    private String name;
    private String type;
    private String login;
    private String password;
    private String url;
    private String weight;
    private String direction;
    private String systemType;
    private boolean useSSL;
    private String monitorInterval;
    private int transactionTimeout;
    /** GETTER
     * The identifier of the sms link
     */
    @JsonGetter("smsLinkId")
    public int getSmsLinkId ( ) { 
        return this.smsLinkId;
    }
    
    /** SETTER
     * The identifier of the sms link
     */
    @JsonSetter("smsLinkId")
    public void setSmsLinkId (int value) { 
        this.smsLinkId = value;
    }
 
    /** GETTER
     * The identifier of the sms link's group
     */
    @JsonGetter("groupId")
    public int getGroupId ( ) { 
        return this.groupId;
    }
    
    /** SETTER
     * The identifier of the sms link's group
     */
    @JsonSetter("groupId")
    public void setGroupId (int value) { 
        this.groupId = value;
    }
 
    /** GETTER
     * The name of the sms link
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * The name of the sms link
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * The protocol of the sms link
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * The protocol of the sms link
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
    /** GETTER
     * The user login. Required for SMPP and Parlay-X delivery.
     */
    @JsonGetter("login")
    public String getLogin ( ) { 
        return this.login;
    }
    
    /** SETTER
     * The user login. Required for SMPP and Parlay-X delivery.
     */
    @JsonSetter("login")
    public void setLogin (String value) { 
        this.login = value;
    }
 
    /** GETTER
     * The user password. Required for SMPP and Parlay-X delivery.
     */
    @JsonGetter("password")
    public String getPassword ( ) { 
        return this.password;
    }
    
    /** SETTER
     * The user password. Required for SMPP and Parlay-X delivery.
     */
    @JsonSetter("password")
    public void setPassword (String value) { 
        this.password = value;
    }
 
    /** GETTER
     * The actual url where the sms is delivered.
     */
    @JsonGetter("url")
    public String getUrl ( ) { 
        return this.url;
    }
    
    /** SETTER
     * The actual url where the sms is delivered.
     */
    @JsonSetter("url")
    public void setUrl (String value) { 
        this.url = value;
    }
 
    /** GETTER
     * The priority of the sms link in the link group.
     */
    @JsonGetter("weight")
    public String getWeight ( ) { 
        return this.weight;
    }
    
    /** SETTER
     * The priority of the sms link in the link group.
     */
    @JsonSetter("weight")
    public void setWeight (String value) { 
        this.weight = value;
    }
 
    /** GETTER
     * The direction of the sms link.
     */
    @JsonGetter("direction")
    public String getDirection ( ) { 
        return this.direction;
    }
    
    /** SETTER
     * The direction of the sms link.
     */
    @JsonSetter("direction")
    public void setDirection (String value) { 
        this.direction = value;
    }
 
    /** GETTER
     * The system type of the sms link.
     */
    @JsonGetter("systemType")
    public String getSystemType ( ) { 
        return this.systemType;
    }
    
    /** SETTER
     * The system type of the sms link.
     */
    @JsonSetter("systemType")
    public void setSystemType (String value) { 
        this.systemType = value;
    }
 
    /** GETTER
     * A flag indicating if SSL should be used.
     */
    @JsonGetter("useSSL")
    public boolean getUseSSL ( ) { 
        return this.useSSL;
    }
    
    /** SETTER
     * A flag indicating if SSL should be used.
     */
    @JsonSetter("useSSL")
    public void setUseSSL (boolean value) { 
        this.useSSL = value;
    }
 
    /** GETTER
     * The monitor interval for the sms link.
     */
    @JsonGetter("monitorInterval")
    public String getMonitorInterval ( ) { 
        return this.monitorInterval;
    }
    
    /** SETTER
     * The monitor interval for the sms link.
     */
    @JsonSetter("monitorInterval")
    public void setMonitorInterval (String value) { 
        this.monitorInterval = value;
    }
 
    /** GETTER
     * The transaction timeout for the sms link.
     */
    @JsonGetter("transactionTimeout")
    public int getTransactionTimeout ( ) { 
        return this.transactionTimeout;
    }
    
    /** SETTER
     * The transaction timeout for the sms link.
     */
    @JsonSetter("transactionTimeout")
    public void setTransactionTimeout (int value) { 
        this.transactionTimeout = value;
    }
 
}
 