/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class StateModel 
        implements java.io.Serializable {

    private int stateId;
    private String stateName;
    private String stateCode;
    private String countryCodeA3;
    /** GETTER
     * The identifier of the state
     */
    @JsonGetter("stateId")
    public int getStateId ( ) { 
        return this.stateId;
    }
    
    /** SETTER
     * The identifier of the state
     */
    @JsonSetter("stateId")
    public void setStateId (int value) { 
        this.stateId = value;
    }
 
    /** GETTER
     * The name of the state
     */
    @JsonGetter("stateName")
    public String getStateName ( ) { 
        return this.stateName;
    }
    
    /** SETTER
     * The name of the state
     */
    @JsonSetter("stateName")
    public void setStateName (String value) { 
        this.stateName = value;
    }
 
    /** GETTER
     * The two letter identifier of the state
     */
    @JsonGetter("stateCode")
    public String getStateCode ( ) { 
        return this.stateCode;
    }
    
    /** SETTER
     * The two letter identifier of the state
     */
    @JsonSetter("stateCode")
    public void setStateCode (String value) { 
        this.stateCode = value;
    }
 
    /** GETTER
     * The three letter identifier for the state's country
     */
    @JsonGetter("countryCodeA3")
    public String getCountryCodeA3 ( ) { 
        return this.countryCodeA3;
    }
    
    /** SETTER
     * The three letter identifier for the state's country
     */
    @JsonSetter("countryCodeA3")
    public void setCountryCodeA3 (String value) { 
        this.countryCodeA3 = value;
    }
 
}
 