/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class TrunkListModel 
        implements java.io.Serializable {

    private List<TrunkModel> trunks;
    /** GETTER
     * The list of trunks
     */
    @JsonGetter("trunks")
    public List<TrunkModel> getTrunks ( ) { 
        return this.trunks;
    }
    
    /** SETTER
     * The list of trunks
     */
    @JsonSetter("trunks")
    public void setTrunks (List<TrunkModel> value) { 
        this.trunks = value;
    }
 
}
 