/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class TrunkModel 
        implements java.io.Serializable {

    private int trunkId;
    private String zone;
    private int capacity;
    private String description;
    private int countDidsOnTrunk;
    /** GETTER
     * The identifier of the trunk
     */
    @JsonGetter("trunkId")
    public int getTrunkId ( ) { 
        return this.trunkId;
    }
    
    /** SETTER
     * The identifier of the trunk
     */
    @JsonSetter("trunkId")
    public void setTrunkId (int value) { 
        this.trunkId = value;
    }
 
    /** GETTER
     * The zone linked to the trunk
     */
    @JsonGetter("zone")
    public String getZone ( ) { 
        return this.zone;
    }
    
    /** SETTER
     * The zone linked to the trunk
     */
    @JsonSetter("zone")
    public void setZone (String value) { 
        this.zone = value;
    }
 
    /** GETTER
     * The maximum capacity of the trunk
     */
    @JsonGetter("capacity")
    public int getCapacity ( ) { 
        return this.capacity;
    }
    
    /** SETTER
     * The maximum capacity of the trunk
     */
    @JsonSetter("capacity")
    public void setCapacity (int value) { 
        this.capacity = value;
    }
 
    /** GETTER
     * The user description of the trunk
     */
    @JsonGetter("description")
    public String getDescription ( ) { 
        return this.description;
    }
    
    /** SETTER
     * The user description of the trunk
     */
    @JsonSetter("description")
    public void setDescription (String value) { 
        this.description = value;
    }
 
    /** GETTER
     * The amount of DIDs currently mapped to the trunk
     */
    @JsonGetter("countDidsOnTrunk")
    public int getCountDidsOnTrunk ( ) { 
        return this.countDidsOnTrunk;
    }
    
    /** SETTER
     * The amount of DIDs currently mapped to the trunk
     */
    @JsonSetter("countDidsOnTrunk")
    public void setCountDidsOnTrunk (int value) { 
        this.countDidsOnTrunk = value;
    }
 
}
 