/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class VoiceUriListModel 
        implements java.io.Serializable {

    private List<VoiceUriModel> voiceUris;
    private int resultCount;
    /** GETTER
     * The list of voice URIs
     */
    @JsonGetter("voiceUris")
    public List<VoiceUriModel> getVoiceUris ( ) { 
        return this.voiceUris;
    }
    
    /** SETTER
     * The list of voice URIs
     */
    @JsonSetter("voiceUris")
    public void setVoiceUris (List<VoiceUriModel> value) { 
        this.voiceUris = value;
    }
 
    /** GETTER
     * The total amount of voice URIs found
     */
    @JsonGetter("resultCount")
    public int getResultCount ( ) { 
        return this.resultCount;
    }
    
    /** SETTER
     * The total amount of voice URIs found
     */
    @JsonSetter("resultCount")
    public void setResultCount (int value) { 
        this.resultCount = value;
    }
 
}
 