/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ZipCodeListModel 
        implements java.io.Serializable {

    private List<ZipCodeModel> cityZipCodes;
    /** GETTER
     * The list of city zip codes
     */
    @JsonGetter("cityZipCodes")
    public List<ZipCodeModel> getCityZipCodes ( ) { 
        return this.cityZipCodes;
    }
    
    /** SETTER
     * The list of city zip codes
     */
    @JsonSetter("cityZipCodes")
    public void setCityZipCodes (List<ZipCodeModel> value) { 
        this.cityZipCodes = value;
    }
 
}
 