/*
 * APIv3SandboxLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/10/2015
 */
package com.voxbone.sandbox.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ZipCodeModel 
        implements java.io.Serializable {

    private String cityName;
    private String zipCode;
    /** GETTER
     * The city name
     */
    @JsonGetter("cityName")
    public String getCityName ( ) { 
        return this.cityName;
    }
    
    /** SETTER
     * The city name
     */
    @JsonSetter("cityName")
    public void setCityName (String value) { 
        this.cityName = value;
    }
 
    /** GETTER
     * The zip code
     */
    @JsonGetter("zipCode")
    public String getZipCode ( ) { 
        return this.zipCode;
    }
    
    /** SETTER
     * The zip code
     */
    @JsonSetter("zipCode")
    public void setZipCode (String value) { 
        this.zipCode = value;
    }
 
}
 